# Generated by Django 6.1.1 on 2026-09-14 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="reported",
            field=models.BooleanField(default=False),
        ),
    ]
